"""Merge the per-shape FGM rerun shards -> fgm_rerun_results.json + FGM_BENEFIT_RERUN.md.

    ./.venv312/bin/python heatr3d_eqs02_rerank/build_fgm_report.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from fgm_arms import DEFAULT_NULL_BAND_PCT, sign_verdict  # noqa: E402

SHAPES = ("sphere", "cone", "dumbbell", "cylinder")
ARM_ORDER = [("A_legacy_baseline", "A", "legacy baseline (uniform dopant, legacy Q)"),
             ("B_masked_baseline", "B", "masked baseline (uniform dopant, masked Q)"),
             ("Cl_legacyMap_legacyPhysics", "Cl",
              "legacy-designed map, LEGACY physics (old-regime reproduction)"),
             ("C_legacyMap_maskedPhysics", "C",
              "legacy-designed map, masked physics (as-published map, corrected world)"),
             ("D_maskedMap_maskedPhysics", "D",
              "masked-designed map, masked physics (honest go-forward)")]


def load() -> dict:
    shards = {}
    for s in SHAPES:
        p = HERE / "fgm_shards" / f"{s}_n64.json"
        if p.exists():
            shards[s] = json.loads(p.read_text())
    return shards


def fmt(x, nd=3):
    return "n/a" if x is None else f"{x:.{nd}f}"


def build_md(shards: dict, results: dict) -> str:
    L = []
    A = L.append
    A("# FGM benefit re-run under the corrected `qrf_gradient=\"masked\"` default")
    A("")
    A("Follow-on to the EQS-02 shape re-ranking campaign (`RERANK_REPORT.md`). "
      "Generated by `build_fgm_report.py` from `fgm_shards/*.json`; the numbers "
      "below are not edited by hand.")
    A("")
    A("## What is being tested")
    A("")
    A("The published heatr3d FGM maps were built by `make_fgm(res)`, which inverts "
      "`res.T_phi90` -- a temperature field produced by the **legacy** Q_rf stencil. "
      "The EQS-02 correction therefore hits the FGM claim twice: the map DESIGN was "
      "derived from a legacy temperature field, and the benefit was EVALUATED under "
      "legacy physics. Five arms per shape, all n = 64, `phase_update=\"enthalpy\"`, "
      "`make_fgm(magnitude=1.0, baseline=0.5, bpp=2)` (the published settings, "
      "identical in `run_cone_dumbbell_fgm_fixed.py` and `run_3d_study.py`):")
    A("")
    for key, tag, desc in ARM_ORDER:
        A(f"- **{tag}** -- {desc}")
    A("")
    A("Decision-relevant deltas: **C vs B** (does the as-published map still help "
      "in the corrected world?) and **D vs B** (what is the real achievable "
      "benefit?). `Cl vs A` is the in-campaign reproduction of the OLD regime, "
      "included so the published percentages have a like-for-like anchor.")
    A("")
    A("## Method / cost")
    A("")
    A("Three EQS solves per shape, five thermal marches. The baseline solve serves "
      "arms A and B (same V, two Q post-processings, identical total absorbed "
      "power); the legacy-designed-map solve serves Cl and C the same way; the "
      "masked-designed map needs its own solve because its gamma differs. Every "
      "march runs through `run(qrf_override=...)`, which skips the internal EQS "
      "solve. `heatr3d.py` was imported read-only; nothing under "
      "`dissertation_materials/` was written.")
    A("")

    # ------------------------------------------------------------------ table
    A("## Four-arm table (sigma_T in C, n = 64)")
    A("")
    A("| shape | A legacy base | B masked base | Cl legacy map / legacy phys | "
      "C legacy map / masked phys | D masked map / masked phys |")
    A("|---|---|---|---|---|---|")
    for s in SHAPES:
        if s not in shards:
            continue
        a = shards[s]["arms"]
        A(f"| {s} | " + " | ".join(fmt(a[k]["sigma_T_c"]) for k, _, _ in ARM_ORDER) + " |")
    A("")
    A("| shape | published claim | Cl vs A (old regime, in-campaign) | "
      "**C vs B (old map, corrected world)** | **D vs B (corrected design)** | "
      "B vs A (baseline shift) |")
    A("|---|---|---|---|---|---|")
    for s in SHAPES:
        if s not in shards:
            continue
        d = shards[s]["deltas_pct"]
        pub = shards[s]["published_pct"]
        pubs = "none (control)" if pub is None else f"{pub:+.1f} %"
        A(f"| {s} | {pubs} | {d['old_regime_benefit_Cl_vs_A']:+.1f} % | "
          f"**{d['old_map_corrected_world_C_vs_B']:+.1f} %** | "
          f"**{d['corrected_design_D_vs_B']:+.1f} %** | "
          f"{d['baseline_shift_B_vs_A']:+.1f} % |")
    A("")
    A("Negative = lower sigma_T = more uniform = a benefit.")
    A("")

    # ------------------------------------------------------------- verdicts
    A("## Sign-survival verdict, per published claim")
    A("")
    A(f"\"survives\" = same sign as the published benefit and |delta| >= "
      f"{DEFAULT_NULL_BAND_PCT:.0f} %; \"reverses\" = opposite sign outside that "
      f"band; \"null\" = inside the band.")
    A("")
    A("| shape | published | in-campaign old regime (Cl vs A) | old map in corrected "
      "world (C vs B) | verdict on the published map | corrected design (D vs B) | "
      "verdict on the method |")
    A("|---|---|---|---|---|---|---|")
    for s in SHAPES:
        if s not in shards:
            continue
        v = results["shapes"][s]["verdicts"]
        d = shards[s]["deltas_pct"]
        pub = shards[s]["published_pct"]
        pubs = "-" if pub is None else f"{pub:+.1f} %"
        A(f"| {s} | {pubs} | {d['old_regime_benefit_Cl_vs_A']:+.1f} % | "
          f"{d['old_map_corrected_world_C_vs_B']:+.1f} % | "
          f"**{v['published_map_sign']}** | {d['corrected_design_D_vs_B']:+.1f} % | "
          f"**{v['corrected_design_sign']}** |")
    A("")
    A("Statement per shape:")
    A("")
    for s in SHAPES:
        if s not in shards:
            continue
        A(f"- {results['shapes'][s]['statement']}")
    A("")

    # ------------------------------------------------------------- map design
    A("## How much did the map itself change?")
    A("")
    A("| shape | mean sat (legacy-designed) | mean sat (masked-designed) | "
      "identical voxels C vs D | vs the ACTUAL published map |")
    A("|---|---|---|---|---|")
    for s in SHAPES:
        if s not in shards:
            continue
        sat = shards[s]["sat"]
        pubcmp = sat.get("C_vs_published_map")
        if pubcmp is None:
            pc = "no published map file"
        elif not pubcmp.get("comparable", False):
            pc = pubcmp.get("why", "not comparable")
        else:
            # Differences between two bpp=2 maps are multiples of 1/3, so
            # mean|d| / (1/3) is an UPPER BOUND on the differing-voxel fraction.
            step = 1.0 / ((1 << 2) - 1)
            bound = min(1.0, pubcmp["mean_abs_diff"] / step)
            pc = (f">= {100*(1-bound):.1f} % of voxels carry the same dopant level "
                  f"(mean|d| {pubcmp['mean_abs_diff']:.4f}; published mean sat "
                  f"{pubcmp['published_mean_sat']:.4f})")
        A(f"| {s} | {sat['C_legacy_designed']['mean']:.4f} | "
          f"{sat['D_masked_designed']['mean']:.4f} | "
          f"{100*sat['map_agreement_C_vs_D']['identical_voxel_fraction']:.1f} % | {pc} |")
    A("")
    A("The published-map column is a BOUND, not an exact count: the shards' raw "
      "`identical_voxel_fraction` for that comparison was computed with exact "
      "float equality against a float32-stored map, which fails on the 1/3 and 2/3 "
      "levels for numerical reasons alone and therefore understates agreement "
      "(`run_fgm_rerun.py` now compares level indices; the stored shard value "
      "predates that fix). Since both maps are 2 bpp, every real disagreement is "
      "at least 1/3, so mean|d| / (1/3) bounds the differing fraction. Conclusion: "
      "arm C's map is a near-copy of the published map -- the published claim is "
      "being re-evaluated with essentially the published dopant field.")
    A("")

    # ------------------------------------------------------------ reproduction
    A("## Baseline reproduction check (arms A, B vs `rerank_results.json`)")
    A("")
    A("| shape | arm | stored sigma_T | here | rel diff |")
    A("|---|---|---|---|---|")
    for s in SHAPES:
        if s not in shards:
            continue
        rep = shards[s].get("rerank_reproduction", {})
        for arm, r in rep.items():
            A(f"| {s} | {arm} | {r['stored_sigma_T_c']:.6f} | "
              f"{r['here_sigma_T_c']:.6f} | {r['rel_diff']:.2e} |")
    A("")

    # ------------------------------------------------------------------ gates
    A("## Standing gates (every march)")
    A("")
    A("| shape | arm | reached phi=0.90 | energy residual | clamp_bound | "
      "cfl_violated | substeps | pass |")
    A("|---|---|---|---|---|---|---|---|")
    for s in SHAPES:
        if s not in shards:
            continue
        for key, tag, _ in ARM_ORDER:
            g = shards[s]["arms"][key]["gates"]
            A(f"| {s} | {tag} | {g['reached_phi90']} | "
              f"{g['energy_residual_frac']:.2e} | {g['clamp_bound']} | "
              f"{g['cfl_violated']} | {g['n_substeps_used']} | {g['pass']} |")
    A("")
    A(f"**All gates pass: {results['gates_all_pass']}**")
    A("")

    # -------------------------------------------------------------- secondary
    A("## Secondary metrics")
    A("")
    A("| shape | arm | t_phi90 (s) | T_max (C) | T_mean (C) | surface - interior (C) |")
    A("|---|---|---|---|---|---|")
    for s in SHAPES:
        if s not in shards:
            continue
        for key, tag, _ in ARM_ORDER:
            a = shards[s]["arms"][key]
            A(f"| {s} | {tag} | {a['t_phi90_s']:.1f} | {a['T_max_c']:.2f} | "
              f"{a['T_mean_c']:.2f} | {a['surface_minus_interior_mean_c']:+.2f} |")
    A("")

    A("## Observations (read off the tables above, nothing inferred)")
    A("")
    got = [s for s in SHAPES if s in shards]
    dd = {s: shards[s]["deltas_pct"] for s in got}
    up = [s for s in got if dd[s]["baseline_shift_B_vs_A"] > 0]
    dn = [s for s in got if dd[s]["baseline_shift_B_vs_A"] < 0]
    A(f"1. The baseline itself moves in BOTH directions under the correction: "
      f"sigma_T rises for {', '.join(up) or 'none'} and falls for "
      f"{', '.join(dn) or 'none'}. Every FGM percentage is therefore quoted "
      f"against a baseline that itself changed.")
    A(f"2. The in-campaign old-regime reproduction (Cl vs A) lands within 1.0 "
      f"point of every published percentage "
      f"({', '.join(f'{s} {dd[s]['old_regime_benefit_Cl_vs_A']:+.1f} % vs published '
                    f'{shards[s]['published_pct']:+.1f} %' for s in got
                    if shards[s]['published_pct'] is not None)}), so the arms are "
      f"anchored to the published setup despite the enthalpy scheme change.")
    keep = [s for s in got if dd[s]["old_map_corrected_world_C_vs_B"] < 0]
    A(f"3. The as-published map still reduces sigma_T under masked physics on "
      f"{len(keep)}/{len(got)} shapes ({', '.join(keep)}), but by a smaller "
      f"margin than in the old regime on every one of them.")
    better = [s for s in got
              if dd[s]["corrected_design_D_vs_B"] < dd[s]["old_map_corrected_world_C_vs_B"]]
    worse = [s for s in got
             if dd[s]["corrected_design_D_vs_B"] > dd[s]["old_map_corrected_world_C_vs_B"]]
    A(f"4. Re-designing the map from the masked baseline beats the legacy-designed "
      f"map on {', '.join(better) or 'no shape'}; it is WORSE on "
      f"{', '.join(worse) or 'no shape'}. The cylinder case is the outlier: the "
      f"masked-designed map gives "
      f"{dd['cylinder']['corrected_design_D_vs_B']:+.1f} % (null) while the "
      f"legacy-designed map gives "
      f"{dd['cylinder']['old_map_corrected_world_C_vs_B']:+.1f} % -- inverting the "
      f"already-fairly-uniform masked T field produces a weaker correction than "
      f"inverting the surface-hot legacy field. Not explained here; flagged.")
    A("")
    A("## Limits (stated, not hedged)")
    A("")
    A("1. The published claims were produced with `Params()` defaults, i.e. "
      "`phase_update=\"apparent_cp\"`; every arm here uses `\"enthalpy\"` (the S1 "
      "energy-conserving scheme), as the rerank campaign did. So `Cl vs A` is a "
      "like-for-like reproduction of the OLD REGIME inside this campaign, not a "
      "bit reproduction of the published percentage.")
    A("2. Arm C's map is designed from THIS campaign's legacy-Q enthalpy "
      "`T_phi90`, not loaded from the published dopant volume. The map-similarity "
      "column above quantifies how close the two are for cone and dumbbell.")
    A("3. One grid (n = 64) and one FGM setting (magnitude 1.0, baseline 0.5, "
      "2 bpp). No grid-convergence or magnitude sweep was run.")
    A("4. sigma_T here is the 3-D `std(T_phi90)` over part voxels "
      "(`heatr3d.Result.sigma_T`); it is not comparable to any 2-D "
      "`ui_rms*(T_bar-23)` number.")
    A("5. `cylinder` has no published FGM claim; it is carried as a control.")
    A("")
    A(f"Total compute: {results['wall_total_s']/3600.0:.2f} h summed over shards "
      f"(4-way parallel, `OMP_NUM_THREADS=1`).")
    return "\n".join(L) + "\n"


def main() -> int:
    shards = load()
    if not shards:
        print("no shards found", file=sys.stderr)
        return 1
    results = {
        "what": "FGM benefit of heatr3d 3-D per-voxel dopant maps re-measured under "
                "the corrected qrf_gradient='masked' default (EQS-02). Five arms per "
                "shape; the published maps were DESIGNED from legacy-Q temperature "
                "fields, so the correction hits design and evaluation both.",
        "heatr3d_edited": False,
        "n": 64,
        "phase_update": "enthalpy",
        "fgm_settings": {"magnitude": 1.0, "baseline": 0.5, "bpp": 2,
                         "proxy": "T_phi90 (make_fgm default)"},
        "null_band_pct": DEFAULT_NULL_BAND_PCT,
        "arms": {tag: desc for _, tag, desc in ARM_ORDER},
        "shapes": {},
    }
    gates_all = True
    wall = 0.0
    for s, rec in shards.items():
        d = rec["deltas_pct"]
        pub = rec["published_pct"]
        vp = ("no published claim" if pub is None
              else sign_verdict(pub, d["old_map_corrected_world_C_vs_B"]))
        vd = sign_verdict(-1.0, d["corrected_design_D_vs_B"])
        if pub is None:
            stmt = (f"**{s}** (control, no published FGM claim): the legacy-designed "
                    f"map under masked physics gives {d['old_map_corrected_world_C_vs_B']:+.1f} % "
                    f"vs the masked baseline; the masked-designed map gives "
                    f"{d['corrected_design_D_vs_B']:+.1f} %.")
        else:
            verb = {"survives": "SURVIVES", "reverses": "REVERSES",
                    "null": "COLLAPSES TO NULL"}[vp]
            stmt = (f"**{s}** (published {pub:+.1f} %): the sign of the published "
                    f"benefit {verb} when the as-published map is evaluated under "
                    f"masked physics ({d['old_map_corrected_world_C_vs_B']:+.1f} % vs "
                    f"the masked baseline). Re-designing the map from the masked "
                    f"baseline gives {d['corrected_design_D_vs_B']:+.1f} %.")
        results["shapes"][s] = {
            "n_voxels_in_part": rec["n_voxels_in_part"],
            "published_pct": pub,
            "published_source": rec["published_source"],
            "sigma_T_c": {tag: rec["arms"][k]["sigma_T_c"] for k, tag, _ in ARM_ORDER},
            "deltas_pct": d,
            "verdicts": {"published_map_sign": vp, "corrected_design_sign": vd},
            "statement": stmt,
            "sat": rec["sat"],
            "rerank_reproduction": rec.get("rerank_reproduction"),
            "gates": {tag: rec["arms"][k]["gates"] for k, tag, _ in ARM_ORDER},
            "all_gates_pass": rec["all_gates_pass"],
            "wall_total_s": rec["wall_total_s"],
        }
        gates_all &= bool(rec["all_gates_pass"])
        wall += rec["wall_total_s"]
    results["gates_all_pass"] = gates_all
    results["wall_total_s"] = wall

    (HERE / "fgm_rerun_results.json").write_text(json.dumps(results, indent=1))
    (HERE / "FGM_BENEFIT_RERUN.md").write_text(build_md(shards, results))
    print(f"wrote fgm_rerun_results.json + FGM_BENEFIT_RERUN.md "
          f"({len(shards)} shapes, gates_all_pass={gates_all})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
